Added git ignore for rider
taras1808/UnityStrategy pull request #10
Opened 2021-03-07 17:20 UTC by DiachukVlad

2021-03-07 17:23 UTC, DiachukVlad commented on .gitignore
> +/.idea/.idea.UnityStrategy/.idea/riderModule.iml
Test comment

2021-03-08 07:41 UTC, taras1808 requested changes

2021-03-11 22:11 UTC, DiachukVlad commented on Assets/Scripts/InventoryUI.cs
> +public class InventoryUI : MonoBehaviour
done

2021-03-11 22:14 UTC, DiachukVlad commented on Assets/Scripts/MouseLook.cs
> +    public GameObject inventoryUI;
Done

2021-03-11 22:14 UTC, DiachukVlad commented on Assets/Scripts/MouseLook.cs
> +        if (inventoryUI.GetComponent<InventoryUI>().showingInventory) return;
done

2021-03-11 22:15 UTC, taras1808 approved these changes

2021-03-12 11:08 UTC, merged